/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterDataAllOf } from './clusterDataAllOf';
import { Relationship } from './relationship';
import { Resource } from './resource';
import { ResourceMetadata } from './resourceMetadata';

export class ClusterData {
    'kind': string;
    'metadata': ResourceMetadata;
    'clusterId': string;
    'controller'?: Relationship;
    'acls': Relationship;
    'brokers': Relationship;
    'brokerConfigs': Relationship;
    'consumerGroups': Relationship;
    'topics': Relationship;
    'partitionReassignments': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "ResourceMetadata"
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "controller",
            "baseName": "controller",
            "type": "Relationship"
        },
        {
            "name": "acls",
            "baseName": "acls",
            "type": "Relationship"
        },
        {
            "name": "brokers",
            "baseName": "brokers",
            "type": "Relationship"
        },
        {
            "name": "brokerConfigs",
            "baseName": "broker_configs",
            "type": "Relationship"
        },
        {
            "name": "consumerGroups",
            "baseName": "consumer_groups",
            "type": "Relationship"
        },
        {
            "name": "topics",
            "baseName": "topics",
            "type": "Relationship"
        },
        {
            "name": "partitionReassignments",
            "baseName": "partition_reassignments",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return ClusterData.attributeTypeMap;
    }
}

