/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Relationship } from './relationship';

export class ConsumerGroupLagSummaryDataAllOf {
    'clusterId': string;
    'consumerGroupId': string;
    'maxLagConsumerId': string;
    'maxLagInstanceId'?: string | null;
    'maxLagClientId': string;
    'maxLagTopicName': string;
    'maxLagPartitionId': number;
    'maxLag': number;
    'totalLag': number;
    'maxLagConsumer': Relationship;
    'maxLagPartition': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "consumerGroupId",
            "baseName": "consumer_group_id",
            "type": "string"
        },
        {
            "name": "maxLagConsumerId",
            "baseName": "max_lag_consumer_id",
            "type": "string"
        },
        {
            "name": "maxLagInstanceId",
            "baseName": "max_lag_instance_id",
            "type": "string"
        },
        {
            "name": "maxLagClientId",
            "baseName": "max_lag_client_id",
            "type": "string"
        },
        {
            "name": "maxLagTopicName",
            "baseName": "max_lag_topic_name",
            "type": "string"
        },
        {
            "name": "maxLagPartitionId",
            "baseName": "max_lag_partition_id",
            "type": "number"
        },
        {
            "name": "maxLag",
            "baseName": "max_lag",
            "type": "number"
        },
        {
            "name": "totalLag",
            "baseName": "total_lag",
            "type": "number"
        },
        {
            "name": "maxLagConsumer",
            "baseName": "max_lag_consumer",
            "type": "Relationship"
        },
        {
            "name": "maxLagPartition",
            "baseName": "max_lag_partition",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return ConsumerGroupLagSummaryDataAllOf.attributeTypeMap;
    }
}

