/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConsumerLagDataAllOf {
    'clusterId': string;
    'consumerGroupId': string;
    'topicName': string;
    'partitionId': number;
    'currentOffset': number;
    'logEndOffset': number;
    'lag': number;
    'consumerId': string;
    'instanceId'?: string | null;
    'clientId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "consumerGroupId",
            "baseName": "consumer_group_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "currentOffset",
            "baseName": "current_offset",
            "type": "number"
        },
        {
            "name": "logEndOffset",
            "baseName": "log_end_offset",
            "type": "number"
        },
        {
            "name": "lag",
            "baseName": "lag",
            "type": "number"
        },
        {
            "name": "consumerId",
            "baseName": "consumer_id",
            "type": "string"
        },
        {
            "name": "instanceId",
            "baseName": "instance_id",
            "type": "string"
        },
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConsumerLagDataAllOf.attributeTypeMap;
    }
}

