/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConsumerGroupData } from './consumerGroupData';
import { ConsumerGroupDataListAllOf } from './consumerGroupDataListAllOf';
import { ResourceCollection } from './resourceCollection';
import { ResourceCollectionMetadata } from './resourceCollectionMetadata';

export class ConsumerGroupDataList {
    'kind': string;
    'metadata': ResourceCollectionMetadata;
    'data': Array<ConsumerGroupData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "ResourceCollectionMetadata"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ConsumerGroupData>"
        }    ];

    static getAttributeTypeMap() {
        return ConsumerGroupDataList.attributeTypeMap;
    }
}

