/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Relationship } from './relationship';

export class ConsumerAssignmentDataAllOf {
    'clusterId': string;
    'consumerGroupId': string;
    'consumerId': string;
    'topicName': string;
    'partitionId': number;
    'partition': Relationship;
    'lag': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "consumerGroupId",
            "baseName": "consumer_group_id",
            "type": "string"
        },
        {
            "name": "consumerId",
            "baseName": "consumer_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "partition",
            "baseName": "partition",
            "type": "Relationship"
        },
        {
            "name": "lag",
            "baseName": "lag",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return ConsumerAssignmentDataAllOf.attributeTypeMap;
    }
}

