/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateTopicRequestDataConfigs } from './createTopicRequestDataConfigs';
import { CreateTopicRequestDataReplicasAssignments } from './createTopicRequestDataReplicasAssignments';

export class CreateTopicRequestData {
    'topicName': string;
    'partitionsCount'?: number;
    'replicationFactor'?: number;
    'replicasAssignments'?: Array<CreateTopicRequestDataReplicasAssignments>;
    'configs'?: Array<CreateTopicRequestDataConfigs>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionsCount",
            "baseName": "partitions_count",
            "type": "number"
        },
        {
            "name": "replicationFactor",
            "baseName": "replication_factor",
            "type": "number"
        },
        {
            "name": "replicasAssignments",
            "baseName": "replicas_assignments",
            "type": "Array<CreateTopicRequestDataReplicasAssignments>"
        },
        {
            "name": "configs",
            "baseName": "configs",
            "type": "Array<CreateTopicRequestDataConfigs>"
        }    ];

    static getAttributeTypeMap() {
        return CreateTopicRequestData.attributeTypeMap;
    }
}

