/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProduceRequestData } from './produceRequestData';
import { ProduceRequestHeader } from './produceRequestHeader';

export class ProduceRequest {
    'partitionId'?: number | null;
    'headers'?: Array<ProduceRequestHeader>;
    'key'?: ProduceRequestData | null;
    'value'?: ProduceRequestData | null;
    'timestamp'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "Array<ProduceRequestHeader>"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "ProduceRequestData"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ProduceRequestData"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ProduceRequest.attributeTypeMap;
    }
}

