/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProduceResponseData } from './produceResponseData';

export class ProduceResponse {
    'clusterId': string;
    'topicName': string;
    'partitionId': number;
    'offset': number;
    'timestamp'?: Date | null;
    'key'?: ProduceResponseData | null;
    'value'?: ProduceResponseData | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "ProduceResponseData"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ProduceResponseData"
        }    ];

    static getAttributeTypeMap() {
        return ProduceResponse.attributeTypeMap;
    }
}

