/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProduceRequestData {
    'type'?: string;
    'subject'?: string | null;
    'subjectNameStrategy'?: string | null;
    'schemaId'?: number | null;
    'schemaVersion'?: number | null;
    'rawSchema'?: string | null;
    'data'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "subjectNameStrategy",
            "baseName": "subject_name_strategy",
            "type": "string"
        },
        {
            "name": "schemaId",
            "baseName": "schema_id",
            "type": "number"
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "number"
        },
        {
            "name": "rawSchema",
            "baseName": "raw_schema",
            "type": "string"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return ProduceRequestData.attributeTypeMap;
    }
}

