/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReassignmentDataAllOf } from './reassignmentDataAllOf';
import { Relationship } from './relationship';
import { Resource } from './resource';
import { ResourceMetadata } from './resourceMetadata';

export class ReassignmentData {
    'kind': string;
    'metadata': ResourceMetadata;
    'clusterId': string;
    'topicName': string;
    'partitionId': number;
    'addingReplicas': Array<number>;
    'removingReplicas': Array<number>;
    'replicas': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "ResourceMetadata"
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "addingReplicas",
            "baseName": "adding_replicas",
            "type": "Array<number>"
        },
        {
            "name": "removingReplicas",
            "baseName": "removing_replicas",
            "type": "Array<number>"
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return ReassignmentData.attributeTypeMap;
    }
}

