/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Relationship } from './relationship';
import { ReplicaDataAllOf } from './replicaDataAllOf';
import { Resource } from './resource';
import { ResourceMetadata } from './resourceMetadata';

export class ReplicaData {
    'kind': string;
    'metadata': ResourceMetadata;
    'clusterId': string;
    'topicName': string;
    'partitionId': number;
    'brokerId': number;
    'isLeader': boolean;
    'isInSync': boolean;
    'broker': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "ResourceMetadata"
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "partitionId",
            "baseName": "partition_id",
            "type": "number"
        },
        {
            "name": "brokerId",
            "baseName": "broker_id",
            "type": "number"
        },
        {
            "name": "isLeader",
            "baseName": "is_leader",
            "type": "boolean"
        },
        {
            "name": "isInSync",
            "baseName": "is_in_sync",
            "type": "boolean"
        },
        {
            "name": "broker",
            "baseName": "broker",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return ReplicaData.attributeTypeMap;
    }
}

