/**
 * REST Admin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: kafka-clients-proxy-team@confluent.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Relationship } from './relationship';

export class TopicDataAllOf {
    'clusterId': string;
    'topicName': string;
    'isInternal': boolean;
    'replicationFactor': number;
    'partitionsCount': number;
    'partitions': Relationship;
    'configs': Relationship;
    'partitionReassignments': Relationship;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        },
        {
            "name": "topicName",
            "baseName": "topic_name",
            "type": "string"
        },
        {
            "name": "isInternal",
            "baseName": "is_internal",
            "type": "boolean"
        },
        {
            "name": "replicationFactor",
            "baseName": "replication_factor",
            "type": "number"
        },
        {
            "name": "partitionsCount",
            "baseName": "partitions_count",
            "type": "number"
        },
        {
            "name": "partitions",
            "baseName": "partitions",
            "type": "Relationship"
        },
        {
            "name": "configs",
            "baseName": "configs",
            "type": "Relationship"
        },
        {
            "name": "partitionReassignments",
            "baseName": "partition_reassignments",
            "type": "Relationship"
        }    ];

    static getAttributeTypeMap() {
        return TopicDataAllOf.attributeTypeMap;
    }
}

